version: "2.1"
services:
  botw-bot:
    image: docker.pkg.github.com/noahkw/botw-bot/botw-bot:latest
    volumes:
      - ${BOTW_BOT_CLONE_DIR}:/app
    restart: always
    depends_on:
      - "db"
    environment:
      - PYTHONUNBUFFERED=1
  db:
    image: postgres:12
    volumes:
      - ${BOTW_BOT_PG_DATA_DIR}:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: XXXXXXXXX
      POSTGRES_USER: botw-bot
