"""add blocked users model

Revision ID: 2f49c0729ee4
Revises: 95cf9ae2faf5
Create Date: 2024-02-03 00:40:44.361775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f49c0729ee4"
down_revision = "95cf9ae2faf5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocked_users",
        sa.Column("_guild", sa.BigInteger(), nullable=False),
        sa.Column("_user", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("_guild", "_user"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blocked_users")
    # ### end Alembic commands ###
