"""create tables custom_role_settinghs and custom_roles

Revision ID: 95cf9ae2faf5
Revises: b6fdae5a4a5a
Create Date: 2024-02-02 00:30:57.593940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95cf9ae2faf5"
down_revision = "b6fdae5a4a5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_role_settings",
        sa.Column("_guild", sa.BigInteger(), nullable=False),
        sa.Column("_role", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("_guild"),
    )
    op.create_table(
        "custom_roles",
        sa.Column("_role", sa.BigInteger(), nullable=False),
        sa.Column("_guild", sa.BigInteger(), nullable=False),
        sa.Column("_user", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("_guild", "_user"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("custom_roles")
    op.drop_table("custom_role_settings")
    # ### end Alembic commands ###
